//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GatewayBelizeOn
{
    using System;
    using System.Collections.Generic;
    
    public partial class BON_USR_USERS
    {
        public int idUser { get; set; }
        public string email { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
    }
}
